# Build your Java project and run tests with Apache Maven.

trigger:
- New_Main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Maven@3
  displayName: 'Build and Run Selenium Tests'
  inputs:
    mavenPomFile: 'eclipse-workspace/SeleniumPractice/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test'
